name: Continuous Integration

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    quality:
        name: Code Quality
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Typecheck
              run: npm run typecheck

            - name: Type Coverage Check
              run: npm run type:coverage
              continue-on-error: true

            - name: Build TypeScript
              run: npm run build:ts

            - name: Lint Code
              run: npm run lint

            - name: Format Check
              run: npm run format:check

            - name: Build CSS
              run: npm run build:css

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-${{ github.sha }}
                  path: |
                      dist/
                      js/
                  retention-days: 1

    test-chromium:
        name: E2E Tests (Chromium)
        runs-on: ubuntu-latest
        needs: quality
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Cache Playwright browsers
              uses: actions/cache@v4
              with:
                  path: ~/.cache/ms-playwright
                  key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

            - name: Install Playwright
              run: npx playwright install --with-deps chromium

            - name: Run E2E Tests
              env:
                  MOCK_GITHUB: '1'
              run: npx playwright test --project=chromium

            - name: Upload test results
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: test-results-chromium
                  path: test-results/
                  retention-days: 7

    test-browsers:
        name: E2E Tests (Firefox/WebKit)
        runs-on: ubuntu-latest
        needs: quality
        if: github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[test-all]')
        strategy:
            matrix:
                browser: [firefox, webkit]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Cache Playwright browsers
              uses: actions/cache@v4
              with:
                  path: ~/.cache/ms-playwright
                  key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

            - name: Install Playwright
              run: npx playwright install --with-deps ${{ matrix.browser }}

            - name: Run E2E Tests
              env:
                  MOCK_GITHUB: '1'
              run: npx playwright test --project=${{ matrix.browser }}

            - name: Upload test results
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: test-results-${{ matrix.browser }}
                  path: test-results/
                  retention-days: 7

    security:
        name: Security Audit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Audit dependencies
              run: npm audit --audit-level=moderate
              continue-on-error: true
